### ISSUE TITLE
are you planning to provide more recent builds

### ISSUE THREAD

**Issue by EugenMayer** [dschense/Proxmox-HP-Proliant-Microserver-Gen8-PCIE-Passthrough#1]
Thank you for your work on this! 

Since Gen8 + Proxmox + PCIpassthrough on NICs becomes more popular i ask myself if you consider providing more recent build of this? Thanks!

**Comment by dschense** [comment]
Ich hab deinen Post im Proxmox Forum gesehen. 

Ich bin bis jetzt nicht mehr dazu gekommen, da ich es bei mir anderst gelöst habe.
Aber ich kann schauen, ob das ganze mit dem neuen Kernel noch funktioniert.
