### ISSUE TITLE
Is the passthrough mode still broken after 1 vm reboot

### ISSUE THREAD

**Issue by EugenMayer** [dschense/Proxmox-HP-Proliant-Microserver-Gen8-PCIE-Passthrough#2]
referring to this https://forum.proxmox.com/threads/hp-proliant-microserver-gen8-raidcontroller-hp-p410-passthrough-probleme.30547/#post-155703

is this still a thing after applying this patch?

Are you currently still running this setup?

**Comment by dschense** [comment]
du solltest das Setup durchführen wie ganz zum Schluss im Forum. Damit funktionierte auch ein VM reboot ohne Probleme.
